config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_attached_file :image, styles: { medium: "400x400#" }, default_url: "http://via.placeholder.com/400x400"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :ingredients, inverse_of: :recipe
  has_many :directions, inverse_of: :recipe

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

  validates :title, :description, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @recipes = Recipe.all.order('created_at DESC')
  end

  def show
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipes_params)
    if @recipe.save!
      redirect_to @recipe, notice: 'Successfully created new recipe'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update_attributes(recipes_params)
      redirect_to @recipe, notice: 'Successfully updated'
    else
      render 'edit', notice: 'Unable to edit recipe!'
    end
  end

  def destroy
    @recipe.destroy!
    redirect_to :back, notice: 'Successfully deleted recipe'
  end

  private

  def recipes_params
    params.require(:recipe).permit(
      :title,
      :description,
      :image,
      ingredients_attributes: [:id, :name, :_destroy],
      directions_attributes: [:id, :step, :_destroy]
    )
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active(path)
    return 'active' if request.path == path
    'active' if request.path == '/recipes' && path == '/'
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %a.navbar-brand
        %img{alt: 'Brand', src: 'http://www.freeiconspng.com/uploads/chief-icon-8.png', width: '25'}
      = link_to 'Recipes App', root_path, class: 'navbar-brand'

    .navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li{class: "#{active('/')}"}= link_to "Home", root_path
        - if user_signed_in?
          %li{class: "#{active('/recipes/new')}"}= link_to "New Recipe", new_recipe_path
          %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li{class: "#{active('/users/sign_in')}"}= link_to "Sign In", new_user_session_path
          %li{class: "#{active('/users/sign_up')}"}= link_to "Sign Up", new_user_registration_path

      %form.navbar-form
        .form-group
          %input.form-control{type:'text', placeholder:"Search" }
          %button.btn.btn-info{ type:'submit' } Search

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Recipe Box
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/navbar'
    .container
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert

      = yield

app/views/recipes/_direction_fields.html.haml
.form-inline.row
  .nested-fields
    .form-group
      = f.input :step, input_html: { class: 'form-control' }
    = link_to_remove_association "Remove", f, class: 'btn btn-info'

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
  - if @recipe.errors.present?
    #errors
      %p
        = @recipes.errors.count
        prevented this form from being submitted!
      %ul
        - @recipe.errors.full_messages.each do |message|
          %li= message
  .panel-body
    = f.input :title, input_html: { class: 'form-control' }
    = f.input :description, input_html: { class: 'form-control' }
    = f.input :image, input_html: { class: 'btn btn-info form-control' }

    .row
      .col-md-6
        %h3 Ingredients
        #ingredients
          = f.simple_fields_for :ingredients do |ingredient|
            = render 'ingredient_fields', f: ingredient
          .links
            = link_to_add_association 'Add Ingredient', f, :ingredients, class: 'btn btn-default add-button'

      .col-md-6
        %h3 Directions
        #directions
          = f.simple_fields_for :directions do |direction|
            = render 'direction_fields', f: direction
          .links
            = link_to_add_association 'Add Step',  f, :directions, class: 'btn btn-default add-button';

  = f.button :submit, { class: 'btn btn-primary' }

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
  .nested-fields
    .form-group
      = f.input :name, input_html: { class: 'form-control ' }
    = link_to_remove_association "Remove", f, class: 'btn btn-info'

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

= link_to 'Back', @recipe, class: 'btn btn-default'

app/views/recipes/index.html.haml
%h1 All Recipes
#recipes
  - @recipes.each_slice(3) do |recipes|
    .row
      - recipes.each do |recipe|
        .col-md-4
          .recipe
            .image_wrapper
              %a{ href: "#{recipe_path(recipe)}" }
                = image_tag recipe.image.url(:medium)
            %h2= link_to recipe[:title], recipe_path(recipe)


= link_to('New Recipe', new_recipe_path, class: 'btn btn-default')

app/views/recipes/new.html.haml
%h1 New Recipe

= render "form"

= link_to "Back", root_path, class: 'btn btn-default'

app/views/recipes/show.html.haml
.main_content
  #recipe_top.row
    .col-md-4
      = image_tag @recipe.image.url(:medium, class: 'recipe_image')
    .col-md-8
      #recipe_info
        %h1= @recipe.title
        %p= @recipe.description
        - if @recipe.user.present?
          %p
            Submitted by
            = @recipe.user[:email]

  .row
    .col-md-6
      #ingredients
        %h2 Ingredients
        %ul
          - @recipe.ingredients.each do |ingredient|
            %li= ingredient[:name]

    .col-md-6
      #directions
        %h2 Directions
        %ul
          - @recipe.directions.each do |direction|
            %li= direction[:step]

  .row
    .col-md-12
      - if user_signed_in?
        = link_to('Edit', edit_recipe_path, class:'btn btn-primary' )
        = link_to 'Delete', @recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
        %br
        %br

      = link_to('Back', recipes_path, class:'btn btn-default' )